language: php

php:
  - 5.4
  - 5.5
  - 5.6

notifications:
  slack: forgotten-hide-out:3SPao4avZI5Ng5PX75v2khys

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev