language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update

script:
- cd application/tests 
- ../vendor/bin/phpunit 

 notifications:
  slack: forgotten-hide-out:3SPao4avZI5Ng5PX75v2khys